server:
  port: 9100 # 伺服器的port號

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?useSSL=false # mysql databases 連接位址
    username: root # database 用戶名
    password: 123456 # database 密碼

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true